
trigger:
- main

pool:
  name: Default
  demands: Unity_2020.3.30


stages:
- stage: CI
  displayName: CI Stage
  jobs:
  - job: build
    pool:
      name: Default
    steps:      
      - task: UnityBuildTask@3
        inputs:
              buildTarget: 'Win64'
              outputPath: '$(Build.BinariesDirectory)'
              outputFileName: 'spacegame'

- stage: CD
  displayName: CD Stage
  jobs:
  - deployment: deploy   
    environment: Staging 
    strategy:
      runOnce:
        deploy:
          steps:
          - script: deployed