
trigger:
- main

pool:
  name: Default
  demands: Unity_2020.3.30


steps:
- task: UnityTestTask@1
  name: unitytest
  inputs:
    testMode: editMode

- script: |
    echo $(unitytest.testResultsOutputPathAndFileName)