
trigger:
- main

pool:
  name: Default
  demands: Unity_2020.3.30


jobs:
  - job: build
    pool:
      name: Default
    steps:      
      - task: UnityBuildTask@3
        inputs:
              buildTarget: 'Win64'
              outputPath: '$(Build.BinariesDirectory)'
              outputFileName: 'spacegame'