# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands: Unity_2020.3.30


# steps:

# #- script: echo "Testing"

#  - task: UnityBuildTask@3
#    inputs:
#      buildTarget: 'Win64'
#      outputPath: '$(Build.BinariesDirectory)'
#      outputFileName: 'spacegame'


stages:
- stage: CI
  displayName: CI Stage
  jobs:
  - job: build
    pool:
      name: Default
    steps:      
      - task: UnityBuildTask@3
        inputs:
              buildTarget: 'Win64'
              outputPath: '$(Build.BinariesDirectory)'
              outputFileName: 'spacegame'

- stage: CD
  displayName: CD Stage
  jobs:
  - job: deploy   
    pool:
      name: Default
      environment: Staging
    steps:
      - script:
        